name: UTM Automation Check

on:
  schedule:
    # Run every 5 minutes
    - cron: '*/5 * * * *'
  workflow_dispatch: # Allow manual trigger

jobs:
  check-bookings:
    runs-on: ubuntu-latest
    
    steps:
    - name: Check for new bookings
      run: |
        curl -X GET https://cursuscapital.co/api/automation/check-bookings
        
    - name: Log result
      run: |
        echo "Automation check completed at $(date)" 